### ISSUE TITLE
Dynamic Imports Error in Deno Deploy

### ISSUE THREAD

**Issue by Abiti-936** [justinawrey/fsrouter#10]
I have worked with Cloudflare Pages & Netlify Edge Functions, What I like the most about these platforms is they provide filebased routing, middleware pattern & http method identification, but when it comes to Deno I have only found these Library that works when Developing my API.

But when I deploy to Deno Deploy, I found that Deno Deploy doesn't allow for dynamic Imports. 
https://deno.land/x/fsrouter@2.4.3/mod.ts?code=#L160

![Screenshot_20220822-202954_Brave](https://user-images.githubusercontent.com/103219498/185983233-8ea78852-4714-4d35-8c1f-2bf24dfa3252.jpg)

Can you fix these Error?

**Comment by justinawrey** [comment]
Thanks for raising this @Abiti-936.  I'd very much like to support Deno Deploy so will see what I can do

**Comment by Maxim-Filimonov** [comment]
@justinawrey any progress on this one ? I'm trying to deploy to deno deploy too.

**Comment by Maxim-Filimonov** [comment]
Digging into this it seem that the easiest way to do that is to copy [fresh approach](https://github.com/denoland/fresh/blob/ba7c78bcc23a89f78d24adda100a9930ca536cff/src/dev/mod.ts#L42)
Which is to generate static file with all the route imports. WDYT?

**Comment by justinawrey** [comment]
yeah, I explored that approach a bit but never really got that far into because life stuff got in the way.  Agreed that its probably the easiest (maybe only??) approach.  I haven't got a huge amount of time to invest in this rn but prs are welcome

**Comment by justinawrey** [comment]
@Abiti-936 @Maxim-Filimonov I'm currently working on deno deploy support

**Comment by justinawrey** [comment]
> @Abiti-936 @Maxim-Filimonov I'm currently working on deno deploy support

This is done.  Deno Deploy is now supported as of [3.1.0](https://github.com/justinawrey/fsrouter/releases/tag/3.1.0)

**Comment by Maxim-Filimonov** [comment]
> > @Abiti-936 @Maxim-Filimonov I'm currently working on deno deploy support
> 
> This is done. Deno Deploy is now supported as of [3.1.0](https://github.com/justinawrey/fsrouter/releases/tag/3.1.0)

That was fast. Thanks heaps! I can have a look to migrate back from rutt.
