### ISSUE TITLE
License?

### ISSUE THREAD

**Issue by yuhr** [justinawrey/fsrouter#20]
License notice is missing. In legal context, I guess this imlicitly means you're not allowing others to use this package. Could you add a `LICENSE` file?

My recommendation is [MPL-2.0](https://en.wikipedia.org/wiki/Mozilla_Public_License), which is a per-file copyleft license, meaning it ensures the source files are accessible by end-users and still preserves ability to be combined with or used within other copyleft/proprietary softwares.

Resources:

- License text: <https://www.mozilla.org/media/MPL/2.0/index.txt>
- FAQ: <https://www.mozilla.org/en-US/MPL/2.0/FAQ/>

**Comment by justinawrey** [comment]
Thanks for the resources!  Added.
